version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - /home/baixing/mongodata:/data/db
    networks:
      - baixingNet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27018:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - baixingNet

  baixing:
    image: xiaoyaolang/python_scrapy_pymongo
    volumes:
      - /home/baixing/repo/Baixing/baixing:/home
    networks:
      - baixingNet

networks:
  baixingNet: